Updated TwabController and made the interface safer
GenerationSoftware/pt-v5-twab-controller pull request #5
Opened 2023-08-07 22:18 UTC by asselstine

2023-08-07 22:38 UTC, asselstine commented on src/libraries/TwabLib.sol
> +    uint32 overwritePeriodStartTime = _overwritePeriodStartTime(PERIOD_LENGTH, PERIOD_OFFSET);
Whoops… realized this line should be passing the end time to compute the overwrite start time.  It shouldn’t be using the current time

2023-08-08 15:37 UTC, asselstine commented on src/TwabController.sol
> +  function isDuringOverwritePeriod(uint32 time) external view returns (bool) {
This name is wrong; it's actually doing the opposite

2023-08-08 16:40 UTC, PierrickGT requested changes

2023-08-08 16:40 UTC, PierrickGT commented on src/libraries/TwabLib.sol
> +    uint32 safeStartTime = _startTime < overwritePeriodStartTime ? _startTime : overwritePeriodStartTime - 1;
Would be useful to create an helper function to retrieve the safe time.

2023-08-08 16:40 UTC, PierrickGT commented on src/libraries/TwabLib.sol
> +    if (startObservation.timestamp != safeEndTime) {
Should be `safeStartTime` no?

2023-08-08 16:40 UTC, PierrickGT commented on src/libraries/TwabLib.sol
> +    uint32 currentPeriod = getTimestampPeriod(PERIOD_LENGTH, PERIOD_OFFSET, currentTime);
Can be inlined.

2023-08-08 16:40 UTC, PierrickGT commented on src/libraries/TwabLib.sol
> +    uint32 currentTime = uint32(block.timestamp);
Should use `endTime` instead of `currentTime`.

2023-08-08 16:40 UTC, PierrickGT commented on src/libraries/TwabLib.sol
>      // Shrink by 1 to ensure periods end on a multiple of PERIOD_LENGTH.
Remove this comment since we removed the `-1`.

2023-08-08 16:40 UTC, PierrickGT commented on src/libraries/TwabLib.sol
> +    return (_timestamp - PERIOD_OFFSET) / PERIOD_LENGTH + 1;
Why was `- 1` removed?

2023-08-08 16:40 UTC, PierrickGT commented on src/libraries/TwabLib.sol
> -      if (_targetTime >= prevOrAtObservation.timestamp) {
We removed this condition cause it's supposed to be handled in the condition above right?

2023-08-08 16:40 UTC, PierrickGT commented on src/libraries/TwabLib.sol
> +  function isDuringOverwritePeriod(
Rename to `isBeforeOverwritePeriod`.

2023-08-10 16:22 UTC, PierrickGT requested changes

2023-08-10 16:22 UTC, PierrickGT commented on src/TwabController.sol
> +    return TwabLib.getBalanceAt(PERIOD_LENGTH, PERIOD_OFFSET, _account.observations, _account.details, _periodEndOnOrAfter(targetTime));
So in `getBalanceAt`, `targetTime` is now always the end of the targeted period?
Maybe the `targetTime` param in TwabLib should be renamed `targetPeriodEndTime`.

2023-08-10 16:22 UTC, PierrickGT commented on src/TwabController.sol
> +        _periodEndOnOrAfter(endTime)
Same here, we could rename the last two params in `TwabLib.getTwabBetween`.

2023-08-10 16:22 UTC, PierrickGT commented on src/TwabController.sol
> +   * @return The start time of the period in which the given timestamp falls
```suggestion
   * @param _timestamp The timestamp to compute the period end time for
   * @return The end time of the period in which the given timestamp falls
```

2023-08-10 16:22 UTC, PierrickGT commented on src/TwabController.sol
> +    uint32 period = TwabLib.getTimestampPeriod(PERIOD_LENGTH, PERIOD_OFFSET, _timestamp);
Can be inlined.

2023-08-10 16:22 UTC, PierrickGT commented on src/TwabController.sol
> +   * The overwrite period is the period during which observations are collated.
```suggestion
   * @dev The overwrite period is the period during which observations are collated.
```

2023-08-10 16:22 UTC, PierrickGT commented on src/libraries/TwabLib.sol
> +    uint32 period = getTimestampPeriod(PERIOD_LENGTH, PERIOD_OFFSET, uint32(block.timestamp));
Can be inlined.

2023-08-10 16:22 UTC, PierrickGT commented on src/libraries/TwabLib.sol
>     * @dev All timestamps prior to the PERIOD_OFFSET fall within period 0.
They fall within period 0 cause before `PERIOD_OFFSET`, a user potentially has a recorded balance?

2023-08-10 16:22 UTC, PierrickGT commented on src/libraries/TwabLib.sol
> +      revert TimestampNotFinalized(_timestamp, overwritePeriodStartTime);
Would make more sense if the error was `PeriodNotFinalized`.
```suggestion
      revert PeriodNotFinalized(_timestamp, overwritePeriodStartTime);
```

2023-08-15 04:48 UTC, asselstine commented on src/TwabController.sol
> +    return TwabLib.getBalanceAt(PERIOD_LENGTH, PERIOD_OFFSET, _account.observations, _account.details, _periodEndOnOrAfter(targetTime));
Yes, targetTime is always "snapped" to the period that ends on it or ends after it.

I feel like `targetPeriodEndTime` isn't quite specific enough.  Perhaps `periodEndOnOrAfterTime`

2023-08-15 04:51 UTC, asselstine commented on src/TwabController.sol
> +        _periodEndOnOrAfter(endTime)
I'll add additional comments for these ones

2023-08-15 05:13 UTC, merged